### ISSUE TITLE
GitHub PAT "metrics-ingestion" has expired

### ISSUE THREAD

**Issue by benbc** [ebmdatalab/metrics#115]
A notification came to Tech Support about a PAT that looks like it's probably part of this component.

> Hey @opensafely-readonly,
>
> Your personal access token (classic) "metrics-ingestion" with repo scope has expired.
>
> If this token is still needed, visit https://github.com/settings/tokens/1382602208/regenerate to generate an equivalent.

This PAT isn't included in the [playbook](https://bennettinstitute-team-manual.pages.dev/tech-group/tech-support/playbook/#github-personal-access-tokens) for expiring PATs.

Please can you handle the expiry and add it to the list in the playbook? You can either have it permanently routed to you or add documentation for Tech Support to follow (you'll see examples of both approaches in the playbook already).

**Comment by lucyb** [comment]
I believe this token is no longer used. I think it was used for a brief time for the metrics cronjobs to authenticate with GitHub, but has now been replaced with some fine-grained tokens (see documentation in the Metrics repo). I have now deleted the token.

As an aside, I noticed the token had read and write access to repos, so if we do need to recreate it, it shouldn't be in the opensafely-readonly account.
