### ISSUE TITLE
Change default invocation in docker image

### ISSUE THREAD

**Issue by ghickman** [ebmdatalab/metrics#37]
Currently we have to invoke the CLI with `dokku run metrics python -m metrics`, otherwise `dokku run metrics` will invoke bash inside the metrics image.

It would save us all a little bit of typing if the image invoked `python -m metrics` by default.

**Comment by madwort** [comment]
We can change what `dokku run` does with [DOKKU_APP_SHELL](https://dokku.com/docs/configuration/environment-variables/), I'm just experimenting to find the correct thing
```dokku config:set metrics DOKKU_APP_SHELL="python -m metrics"```

**Comment by madwort** [comment]
closing as "not worth fixing"
