### ISSUE TITLE
Use grafana-dashboard-manager to backup dashboards

### ISSUE THREAD

**Issue by madwort** [ebmdatalab/metrics#47]
python app https://github.com/Beam-Connectivity/grafana-dashboard-manager that will generate a set of JSON files.

**Comment by sebbacon** [comment]
I also found this, in case helpful 

https://github.com/NovatecConsulting/grafana-dashboard-synchronizer

**Comment by madwort** [comment]
following on from [discussion](https://bennettoxford.slack.com/archives/C0609NHNHST/p1700834985265029?thread_ts=1700834466.674639&cid=C0609NHNHST) 

The idea was to backup the JSON representation of the dashboards as well as the representation contained in the database backups we're already doing. In principle these tools can do this easily, but I think actually doing it & storing it somewhere would be fiddly. In the past auto-committing to github repos has been a useful tool - but I don't feel comfortable doing it in the current context of OpenSAFELY work, as it comes into conflict with having branch protection / enforcing CI / etc. I think we'd need to e.g. have the output in a separate repo to the tooling with lower security defaults (i.e. not put these JSON dashboards in the `metrics` repo). In discussion, we also weren't sure - after the current initial development work - who is going to be maintaining these dashboards & whether the assumption that they're very familiar with Github for tracking changes is correct. The steer was "a /little/ bit of effort", so I think doing this would be over-budget. Therefore I'm closing as WILLNOTFIX.
