### ISSUE TITLE
Verify that grafana autoupdates are deploying correctly

### ISSUE THREAD

**Issue by madwort** [ebmdatalab/metrics#61]
* https://github.com/ebmdatalab/metrics/pull/49 was correctly tested & auto-merged, but the deployment process did not run - in general the Grafana deployment job has been running on  branches but not on the merge to `main`.
* @madwort noticed that the deployment process appeared to have run correctly before https://github.com/ebmdatalab/metrics/pull/35 but not afterwards, so reverted it https://github.com/ebmdatalab/metrics/pull/58 & did a follow-up test https://github.com/ebmdatalab/metrics/pull/59 which did then deploy correctly
* it's a bit unclear why this should be happening, or whether this was the correct fix
* BLOCKED waiting until the next dependabot auto-update & see what happens then

**Comment by madwort** [comment]
auto-update PR was merged https://github.com/ebmdatalab/metrics/pull/75

**Comment by madwort** [comment]
see also https://github.com/ebmdatalab/metrics/pull/87

**Comment by madwort** [comment]
manually deployed the update in #75 https://github.com/ebmdatalab/metrics/actions/runs/7399781682

**Comment by madwort** [comment]
as far as I can see, the GHA workflows in this repo (inc. the other tests) do not always run after the merge to main, and the GHA docs don't have much to say about it - I think they do if there's a merge commit but they don't if it applies cleanly. weirdly, I /thought/ there was a repo setting (something to the effect of "always re-run CI on main after merging a PR") but I just had a look & can't find anything like that here & now :/ I think we can easily widen the parameters in the `on:` section of the grafana deployment GHA to ensure that it runs, but then we're back to the previous issue that the deployment returns an error if there is no new version of grafana to deploy (which is most of the time).

**Comment by madwort** [comment]
hmm, maybe a weekly trigger would do the job

**Comment by madwort** [comment]
@lucyb I've removed myself from this ticket, as I think it's your team's responsibility now - hope that's ok?

**Comment by lucyb** [comment]
There's an example here: https://github.com/ebmdatalab/metrics/actions/runs/7570488663
