### ISSUE TITLE
Output checking dashboard: change displayed charts 

### ISSUE THREAD

**Issue by cewalters** [ebmdatalab/metrics#99]
On the output checking dashboard, the temporal range of interest can be adjusted.  This change affects only the 2 charts on the right hand side and does not affect the charts on the left hand side.

1) Request for the left-hand side charts to also be updated to match the temporal range selected;
2) The current behaviour could lead the user to misinterpret the charts being displayed, ie they may assume that the left hand side charts already are for the selected temporal range.

I think the main priority is to ensure what is displayed is not misleading (MUST HAVE), followed by creating the charts as suggested in 1 (WOULD LIKE TO HAVE).

Slack discussion with additional context [here](https://bennettoxford.slack.com/archives/C065F8P58AW/p1705664720985949).

**Comment by lucyb** [comment]
I've updated the charts on the left-hand side so they update according to the date picker (temporal range of interest). If I don't hear back I'll consider this ticket to be complete. Otherwise, please reopen if something doesn't look right.
